# Generated by Django 3.2.3 on 2021-07-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Тип акции')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='money',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(default='', max_length=100, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='company',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021, verbose_name='Год основания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type_company',
            field=models.CharField(max_length=100, verbose_name='Тип компании'),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.AddField(
            model_name='company',
            name='stock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='companies.stock'),
        ),
    ]
