# Generated by Django 3.2.3 on 2021-07-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210705_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='stock',
        ),
        migrations.AddField(
            model_name='company',
            name='stock',
            field=models.ManyToManyField(default=0, to='companies.Stock'),
        ),
    ]
